### ISSUE TITLE
お願いがあります！

### ISSUE THREAD

**Issue by Ryuraryuryu** [siloneco/Omikuji#13]
御籤プラグインを1.19に対応させてくれませんか？
どうしても貴方の作った実用的な御籤を設置したいです！
よろしくお願いします！

**Comment by siloneco** [comment]
私のプラグインを使用して頂きありがとうございます。
対応を行い、Paper 1.19.4 で正常に動作することを確認しました。
問題等ございましたらお気軽にご連絡ください。よろしくお願いします。

ダウンロード: https://github.com/siloneco/Omikuji/releases/tag/1.0.5

**Comment by Ryuraryuryu** [comment]
ありがとうございます！
