### ISSUE TITLE
アップデートについて

### ISSUE THREAD

**Issue by ookami0104** [siloneco/Omikuji#7]
こんにちははじめまして
おーかみといいます。

もうすぐお正月が近づいており、こちらのプラグインを使用させて頂こうと思いサーバーに導入致しました。
私のサーバーは1.17.1で建てております。
もしかしたら動作するかも？と思い、導入してみましたが、正しく動作しませんでした。

もし宜しければ、こちらのプラグインを1.17.1にアップデートしていただけないでしょうか。
誠に勝手ながらな発言ですが貴方のプラグインはとても使いやすくサーバーを利用してくださるプレイヤー様も喜んでくれると思います。

お返事お待ちしております。

**Comment by siloneco** [comment]
こんにちは。私のプラグインを使用することを検討していただきありがとうございます。
今確認しましたところ、使用しているライブラリが 1.16 までしか対応していないバージョンのものでしたので、それを更新し、1.17.1 で正常に動作することを確認しました。
つきましては、バージョン 1.0.3 を[こちら](https://github.com/siloneco/Omikuji/releases/tag/1.0.3)からダウンロードして再度検証していただければありがたいです。
よろしくお願いします。

Release: https://github.com/siloneco/Omikuji/releases/tag/1.0.3

**Comment by ookami0104** [comment]
@siloneco 

とても素早い対応ありがとうございます。
嬉しいです(●︎´▽︎`●︎)
有難く、こちらのプラグインを使用させていただきますm(*_ _)m
